### ISSUE TITLE
const reassign issue in web-core-sdk

### ISSUE THREAD

**Issue by shubham-gup** [exotel/exotel-ip-calling-crm-websdk#4]
This repo uses "@exotel-npm-dev/webrtc-client-sdk" as a dep, which has a `const` reassign issue. Where `const logger` is being reassigned on line 1277.

This is in file `@exotel-npm-dev/web-core-sdk/src/sipjsphone.js` line 41. Please change it to `let/var` since this is giving us a build issue on our app.

I would've raised the fix on my own but I don't think `@exotel-npm-dev` repo is public.

**Comment by ExoAbhishek** [comment]
Resolved in PR https://github.com/exotel/exotel-ip-calling-crm-websdk/pull/5
